services:
  - type: web
    name: gmail-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app1.py
    envVars:
      - key: PORT
        value: 5000
